---
- hosts: localhost
  gather_facts: no
  vars:
     vcenter_server: "[vcenter address]"
    vcenter_user: "[ user ]"
    vcenter_pass: "[ passwd ] "
    datacenter_name: "Gotham"
   cluster_name: "Arkham"
 tasks:
 - name: Clone the template
    vmware_guest:
         hostname: "{{ vcenter_server }}"
         username: "{{ vcenter_user }}"
         password: "{{ vcenter_pass }}"
         validate_certs: False
         name: [ name of the vm ]
         template: [ name of the template in the vcenter: template-ubuntu16s ] 
         datacenter: "{{ datacenter_name }}"
         folder: /{{ datacenter_name }}/vm
         cluster: "{{ cluster_name }}"
         datastore: [name of the datastore: example --> "tegile_linuxds1"]
    networks:
    - name: vlan 100  -----→ example vlan 
       ip: 172.0.0.0 ---→ example ip
       netmask: 255.255.255.0
       gateway: 172.16.100.7 
       type: static
       dns_servers: 172.16.100.36
    customization:
        hostname: [ name of the host: "name of the host" ] 
        dns_servers:
        - 172.0.0.1
        - 172.0.0.2
    state: poweredon
    wait_for_ip_address: yes
delegate_to: localhost
